version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "02:00"
      timezone: "Europe/Rome"
    open-pull-requests-limit: 2
    groups:
      sqlite:
        patterns:
          - "SQLitePCLRaw.*"
          - "sqlite*"
      test-deps:
        patterns:
          - "coverlet.*"
          - "xunit*"
      runtime:
        patterns:
          - "Microsoft.*"
          - "System.*"
