name: build-test-coverage

on:
  push:
    branches: [ main, chore/restore-axisvariable ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  COVERAGE_MIN: 75

jobs:
  coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Install ReportGenerator
        shell: pwsh
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # Eseguiamo i test una volta sola
      - name: Run tests + collect coverage (Core)
        shell: pwsh
        run: >
          dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Debug
          /p:CollectCoverage=true
          /p:CoverletOutput=TestResults/Coverage/
          /p:CoverletOutputFormat=cobertura
          "/p:ExcludeByFile=**/*LegacyExtensions.cs;**/Logging*.cs;**/Persistence/*.cs"

      - name: Run tests + collect coverage (Sqlite)
        shell: pwsh
        run: >
          dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Debug
          /p:CollectCoverage=true
          /p:CoverletOutput=TestResults/Coverage/
          /p:CoverletOutputFormat=cobertura
          "/p:ExcludeByFile=**/*LegacyExtensions.cs;**/Logging*.cs;**/Persistence/*.cs"

      - name: Merge + Gate + Step Summary
        id: gate
        shell: pwsh
        run: |
          $out = pwsh ./tools/coverage.ps1 -MinLine $env:COVERAGE_MIN 2>&1 | Tee-Object -Variable _out
          $out | Out-String | Out-File -FilePath coverage-summary.md -Encoding utf8
          Get-Content coverage-summary.md -Raw | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: |
            TestResults/MergedCoverage/Cobertura.xml
            TestResults/MergedCoverage/Summary.txt
            tests/**/TestResults/Coverage/coverage.cobertura.xml
