name: build-test-coverage

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
          cache: true
          cache-dependency-path: |
            **/*.csproj
            **/global.json
            **/nuget.config

      - name: Restore
        run: dotnet restore Progesi.sln

      - name: Build (Release)
        run: dotnet build Progesi.sln -c Release --no-restore

      - name: Test (Release)
        run: dotnet test Progesi.sln -c Release --no-build --logger "trx;LogFileName=test-results.trx"

      - name: Publish test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/*.trx
            **/TestResults/**/*.trx
          if-no-files-found: ignore
