name: build-test-coverage

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build-test-coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Install ReportGenerator tool
        shell: pwsh
        run: dotnet tool install -g dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # 👉 Genera SEMPRE i report Cobertura nel runner
      - name: Run tests and collect coverage (Coverlet)
        shell: pwsh
        run: |
          dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Debug `
            /p:CollectCoverage=true `
            /p:CoverletOutput=TestResults/Coverage/ `
            /p:CoverletOutputFormat=cobertura

          dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Debug `
            /p:CollectCoverage=true `
            /p:CoverletOutput=TestResults/Coverage/ `
            /p:CoverletOutputFormat=cobertura

      - name: Coverage gate & summary
        shell: pwsh
        env:
          COVERAGE_MIN: '75'   # alziamo a 80 quando siamo stabili
        run: pwsh ./tools/coverage.ps1 -MinLine $env:COVERAGE_MIN

      - name: Generate HTML coverage (optional)
        if: always()
        shell: pwsh
        run: |
          $merged = Join-Path $PWD "TestResults/MergedCoverage/Cobertura.xml"
          if (Test-Path $merged) {
            reportgenerator "-reports:$merged" "-targetdir:TestResults/CoverageHtml" "-reporttypes:HtmlInline_AzurePipelines"
          }

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            TestResults/MergedCoverage/**
            TestResults/CoverageHtml/**
          if-no-files-found: ignore
