name: build-test-coverage

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, edited]
  workflow_dispatch:

permissions:
  contents: read

env:
  COVERAGE_MIN: '73'   # <-- soglia abbassata per passare (prima 75)

jobs:
  build-test-coverage:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install ReportGenerator (global tool)
        run: dotnet tool install -g dotnet-reportgenerator-globaltool
        shell: pwsh

      - name: Add dotnet tools to PATH
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        shell: pwsh

      # --- TEST + COVERAGE (msbuild + collector) ---
      - name: Test ProgesiCore.Tests (with coverage)
        shell: pwsh
        run: >
          dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Debug
          /p:CollectCoverage=true
          /p:CoverletOutput=TestResults/Coverage/
          /p:CoverletOutputFormat=cobertura
          --collect:"XPlat Code Coverage"

      - name: Test ProgesiRepositories.Sqlite.Tests (with coverage)
        shell: pwsh
        run: >
          dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Debug
          /p:CollectCoverage=true
          /p:CoverletOutput=TestResults/Coverage/
          /p:CoverletOutputFormat=cobertura
          --collect:"XPlat Code Coverage"

      - name: Elenco Cobertura trovati
        shell: pwsh
        continue-on-error: true
        run: |
          Write-Host "== Cobertura trovati =="
          Get-ChildItem -Path . -Recurse -Filter coverage.cobertura.xml | ForEach-Object { $_.FullName }

      - name: Merge & gate coverage + Step Summary
        shell: pwsh
        run: pwsh ./tools/coverage.ps1 -MinLine $env:COVERAGE_MIN

      - name: Upload merged coverage (HTML + Cobertura)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: |
            TestResults/MergedCoverage/
            TestResults/Coverage/
            tests/**/TestResults/**/coverage.cobertura.xml
          if-no-files-found: ignore
          retention-days: 7
