name: CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - "Progesi.sln"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main ]
    paths:
      - "src/**"
      - "tests/**"
      - "Progesi.sln"
      - ".github/workflows/ci.yml"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_NOLOGO: 1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build -c Release --no-restore /m

      - name: Test + Coverage (XPlat collector)
        run: >
          dotnet test Progesi.sln
          -c Release
          --no-build
          --logger "trx;LogFileName=test-results.trx"
          --results-directory "out\test-results"
          --collect "XPlat Code Coverage"

      - name: Install ReportGenerator
        run: dotnet tool update --global dotnet-reportgenerator-globaltool

      - name: Add dotnet tools to PATH
        shell: pwsh
        run: echo "$env:USERPROFILE\.dotnet\tools" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Generate HTML report
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path coverage-html | Out-Null
          reportgenerator -reports:"out/test-results/**/coverage.cobertura.xml" -targetdir:"coverage-html" -reporttypes:"HtmlInline_AzurePipelines;Cobertura"

      - name: Upload coverage (HTML + Cobertura)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-html
          if-no-files-found: warn
          path: |
            out/test-results/**/coverage.cobertura.xml
            coverage-html/**

      - name: Upload TRX test logs
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          if-no-files-found: warn
          path: out/test-results/**/*.trx
