name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: [ '**/*.md' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Locate solution filter (fallback a .sln)
        id: sln
        shell: pwsh
        run: |
          $slnf = Get-ChildItem -Recurse -Filter 'Progesi.CI.slnf' | Select-Object -First 1
          if ($slnf) { $p=$slnf.FullName } else { $p=(Get-ChildItem -Recurse -Filter '*.sln' | Select-Object -First 1).FullName }
          echo "SLNF=$p" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Restore & Build
        shell: pwsh
        run: |
          dotnet restore "$Env:SLNF"
          dotnet build "$Env:SLNF" -c Release --no-restore

      - name: Test - Core
        shell: pwsh
        run: dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Release --no-restore

      - name: Build - Sqlite.Tests (win-x64)
        shell: pwsh
        run: dotnet build tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Release -r win-x64 --no-restore

      - name: Test - Sqlite (win-x64)
        shell: pwsh
        run: dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Release -r win-x64 --no-restore

      - name: Diagnostics dump (always)
        if: always()
        shell: pwsh
        run: tools/gha-dump.ps1
