name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK (8.x + 6.x)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Setup MSBuild (VS BuildTools)
        uses: microsoft/setup-msbuild@v2

      - name: Restore
        shell: pwsh
        run: dotnet restore .\Progesi.sln

      - name: Build (Release, no-restore)
        shell: pwsh
        run: dotnet build .\Progesi.sln -c Release --no-restore

      - name: Test (Release) + Coverage (collector)
        shell: pwsh
        run: |
          dotnet test .\tests\ProgesiRepositories.Sqlite.Tests\ProgesiRepositories.Sqlite.Tests.csproj `
            -c Release --no-build `
            --logger "trx;LogFileName=tests.trx" `
            --collect:"XPlat Code Coverage"

      - name: Generate coverage HTML
        shell: pwsh
        run: |
          dotnet tool update -g dotnet-reportgenerator-globaltool
          $rg = "$HOME\.dotnet\tools\reportgenerator.exe"
          & $rg -reports:**\coverage.cobertura.xml -targetdir:CoverageReport -reporttypes:Html

      - name: Upload Test Results & Coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: |
            **/TestResults/*.trx
            **/TestResults/**/coverage.cobertura.xml
            CoverageReport/
