name: CI

on:
  push:
    branches:
      - main
      - chore/**
      - feature/**
      - fix/**
  pull_request:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  windows-tests:
    name: "CI Windows x64 tests"
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore tests
        run: dotnet restore tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj

      - name: Build tests (Release)
        run: dotnet build tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Release --no-restore

      # Esegue i test in Release senza ricompilare; VSTest troverà la DLL in bin\Release\net48
      - name: Test (TRX + Coverage)
        run: dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Release --no-build --collect:"XPlat Code Coverage" -l "trx;LogFileName=ProgesiCore.trx"

      - name: Upload test results (.trx)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-trx
          path: |
            **/*.trx
            **/TestResults/**/*.trx
          if-no-files-found: warn

      - name: Upload coverage (cobertura/opencover)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: |
            **/TestResults/**/coverage.cobertura.xml
            **/TestResults/**/coverage.opencover.xml
          if-no-files-found: warn
