name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: windows-latest
    env:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET (8.x)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore
        shell: pwsh
        run: |
          $slnf = Get-ChildItem -Recurse -Filter 'Progesi.CI.slnf' | Select-Object -First 1
          if (-not $slnf) { throw "Progesi.CI.slnf not found" }
          "SLNF=$($slnf.FullName)" | Out-File -FilePath $Env:GITHUB_ENV -Append
          dotnet restore "$Env:SLNF"

      - name: dotnet format (verify)
        shell: pwsh
        run: dotnet format whitespace "$Env:SLNF" --verify-no-changes

      - name: Build
        shell: pwsh
        run: dotnet build "$Env:SLNF" -c Release --no-restore

      - name: Test (quick)
        shell: pwsh
        run: |
          $tests = @('tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj') | Where-Object { Test-Path $_ }
          foreach ($t in $tests) {
            Write-Host "==> dotnet test $t"
            dotnet test $t -c Release --no-build
          }
