name: CI

on:
  push:
    branches:
      - main
      - stabilize/**
      - ci/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test:
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore (NuGet)
        run: nuget restore Progesi.sln

      - name: Build (Release)
        run: msbuild Progesi.sln /m /p:Configuration=Release /p:RunCodeAnalysis=false

      - name: Test + Coverage (Sqlite tests)
        run: >
          dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj
          -c Release
          --logger "trx;LogFileName=tests.trx"
          --collect:"XPlat Code Coverage"
          --results-directory TestResults

      - name: Generate coverage report (HTML)
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'TestResults/**/coverage.cobertura.xml'
          targetdir: 'CoverageReport'
          reporttypes: 'Html;TextSummary'

      - name: Upload artifacts (reports & trx)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-testresults
          path: |
            CoverageReport/**
            TestResults/**/*.trx
