name: CI

on:
  push:
    branches: [ main, "feature/**", "chore/**", "tests/**" ]
    paths-ignore:
      - "**/*.md"
      - "**/*.png"
      - "**/*.jpg"
      - "**/*.gif"
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET SDKs
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore

      - name: Build (Release - selective)
        run: |
          dotnet build src/ProgesiCore/ProgesiCore.csproj --configuration Release --no-restore
          dotnet build src/ProgesiRepositories.InMemory/ProgesiRepositories.InMemory.csproj --configuration Release --no-restore
          dotnet build src/ProgesiRepositories.Sqlite/ProgesiRepositories.Sqlite.csproj --configuration Release --no-restore

      - name: Test ProgesiCore (x64 + coverage)
        run: dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" -- RunConfiguration.TargetPlatform=x64 -l "trx;LogFileName=core.trx" --verbosity normal

      - name: Test ProgesiRepositories.Sqlite (x64 + coverage)
        run: dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj --configuration Release --no-build --collect:"XPlat Code Coverage" -- RunConfiguration.TargetPlatform=x64 -l "trx;LogFileName=sqlite.trx" --verbosity normal

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: "**/coverage.cobertura.xml"
          targetdir: "coveragereport"
          reporttypes: "HtmlInline;TextSummary"
          historydir: "coveragereport-history"

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coveragereport

      - name: Publish test results (trx)
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: "VSTest Results"
          path: "**/*.trx"
          reporter: dotnet-trx
