name: CI

on:
  push:
    branches:
      - main
      - develop
      - "release/**"
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  pull_request:
    branches:
      - main
      - develop
      - "release/**"
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    name: Build & Test
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore Progesi.sln

      - name: Build (Release)
        run: dotnet build Progesi.sln -c Release --no-restore

      - name: Test with coverage
        run: >
          dotnet test Progesi.sln -c Release --no-build
          --logger "trx;LogFileName=test-results.trx"
          --results-directory "${{ runner.temp }}/test-results"
          --collect "XPlat Code Coverage"

      - name: Collect artifacts
        shell: pwsh
        run: |
          New-Item -Type Directory -Force CoverageReport | Out-Null
          New-Item -Type Directory -Force TestResults    | Out-Null
          Get-ChildItem "${{ runner.temp }}/test-results" -Recurse -Filter "coverage.cobertura.xml" |
            ForEach-Object {
              Copy-Item $_.FullName (Join-Path CoverageReport ("coverage-" + $_.Directory.Name + ".xml")) -Force
            }
          Get-ChildItem "${{ runner.temp }}/test-results" -Recurse -Filter "*.trx" |
            Copy-Item -Destination TestResults -Force

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport
          path: CoverageReport
          if-no-files-found: warn

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: TestResults
          if-no-files-found: warn
