name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    runs-on: windows-latest
    env:
      SLNF: ${{ github.workspace }}\Progesi.CI.slnf

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET (8.x)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x

      - name: Restore (solution filter)
        run: dotnet restore "$Env:SLNF"

      - name: Build (Release)
        run: dotnet build "$Env:SLNF" -c Release --no-restore

      - name: Test – ProgesiCore.Tests
        run: dotnet test tests/ProgesiCore.Tests/ProgesiCore.Tests.csproj -c Release --no-build

      # ---- Sqlite: restore + build + test (RID win-x64) ----
      - name: Restore – ProgesiRepositories.Sqlite.Tests (RID win-x64)
        run: dotnet restore tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -r win-x64

      - name: Build – ProgesiRepositories.Sqlite.Tests (RID win-x64)
        run: dotnet build tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Release -r win-x64 --no-restore

      - name: Test – ProgesiRepositories.Sqlite.Tests (RID win-x64)
        run: dotnet test tests/ProgesiRepositories.Sqlite.Tests/ProgesiRepositories.Sqlite.Tests.csproj -c Release -r win-x64 --no-build
      # ------------------------------------------------------

      - name: Dump on failure
        if: failure()
        shell: pwsh
        run: tools/gha-dump.ps1
