name: PR Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]

# il labeler deve poter leggere i contenuti e scrivere le label
permissions:
  contents: read
  pull-requests: write

jobs:
  label:
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft }}  # opzionale: salta i draft
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
