name: PR Labeler
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited, ready_for_review]
permissions:
  contents: read
  issues: write
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Run labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: false
          dot: true
