name: release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read
  packages: write

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x

      - name: Restore
        run: dotnet restore Progesi.CI.slnf

      - name: Build
        run: dotnet build Progesi.CI.slnf -c Release --no-restore

      - name: Pack
        run: dotnet pack src/ProgesiCore/ProgesiCore.csproj -c Release -o ./nuget --no-build

      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/*.nupkg
          if-no-files-found: error

  release:
    needs: pack
    runs-on: ubuntu-latest

    env:
      OWNER: ${{ github.repository_owner }}
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      # Se non c'è GPR_PAT, uso il GITHUB_TOKEN
      GPR_TOKEN: ${{ secrets.GPR_PAT != '' && secrets.GPR_PAT || github.token }}

    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget

      # ---------------- NuGet.org ----------------
      - name: Push to NuGet.org
        if: env.NUGET_API_KEY != ''
        run: |
          dotnet nuget push "nuget/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "${{ env.NUGET_API_KEY }}" \
            --skip-duplicate

      # ------------- GitHub Packages -------------
      - name: Configure GPR source (username+password)
        if: env.GPR_TOKEN != ''
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/${{ env.OWNER }}/index.json" \
            --name "github" \
            --username "${{ env.OWNER }}" \
            --password "${{ env.GPR_TOKEN }}" \
            --store-password-in-clear-text

      - name: Push to GitHub Packages (GPR)
        if: env.GPR_TOKEN != ''
        run: |
          dotnet nuget push "nuget/*.nupkg" \
            --source "github" \
            --skip-duplicate

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: nuget/*.nupkg
          generate_release_notes: true
