name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # es: v1.0.1

permissions:
  contents: write
  packages: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      # Calcola la versione dal tag se presente (es. v1.0.1 -> 1.0.1)
      - name: Compute version (if tag)
        id: vars
        shell: bash
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            echo "VER=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
          fi

      # Pack SOLO i csproj sotto ./src; se c'è un tag forza /p:Version=...
      - name: Pack (src only)
        shell: bash
        run: |
          if [[ -n "${{ steps.vars.outputs.VER }}" ]]; then
            dotnet pack ./src/*/*.csproj -c Release --no-build -o ./nupkg /p:Version=${{ steps.vars.outputs.VER }}
          else
            dotnet pack ./src/*/*.csproj -c Release --no-build -o ./nupkg
          fi

      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg/*.nupkg

  release:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Compute version (from tag)
        id: vars
        if: startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: echo "VER=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"

      # --- Publish to nuget.org (solo i pacchetti della versione del tag) -----
      - name: Publish to NuGet.org
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "./nupkg/*.${{ steps.vars.outputs.VER }}.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "$NUGET_API_KEY" \
            --skip-duplicate

      # --- Publish to GitHub Packages (usa esplicitamente --api-key) -----------
      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        env:
          OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push "./nupkg/*.${{ steps.vars.outputs.VER }}.nupkg" \
            --source "https://nuget.pkg.github.com/$OWNER/index.json" \
            --api-key "$GITHUB_TOKEN" \
            --skip-duplicate

      # --- GitHub Release con i nupkg della versione ---------------------------
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./nupkg/*.${{ steps.vars.outputs.VER }}.nupkg
