name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'   # es: v1.0.5

permissions:
  contents: write   # per creare la GitHub Release
  packages: write   # per pubblicare su GitHub Packages

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      # Se tutti i progetti non-voluti sono IsPackable=false, questo basta.
      # In alternativa potresti packare solo i csproj sotto ./src.
      - name: Pack
        run: dotnet pack -c Release --no-build -o ./nupkg

      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg/*.nupkg

  release:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # --- Publish to nuget.org ------------------------------------------------
      - name: Publish to NuGet.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "$NUGET_API_KEY" \
            --skip-duplicate

      # --- Configure GitHub Packages source -----------------------------------
      - name: Configure GitHub Packages source (GPR)
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
        run: |
          dotnet nuget remove source github || true
          dotnet nuget add source "https://nuget.pkg.github.com/$OWNER/index.json" \
            --name "github" \
            --username "$GITHUB_ACTOR" \
            --password "$GITHUB_TOKEN" \
            --store-password-in-clear-text
          dotnet nuget list source

      # --- Publish to GitHub Packages -----------------------------------------
      - name: Publish to GitHub Packages
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "github" \
            --skip-duplicate

      # --- Crea la GitHub Release con gli artifacts ----------------------------
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./nupkg/*.nupkg
