      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        env:
          OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_PAT: ${{ secrets.GPR_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          VER="${{ steps.vars.outputs.VER }}"
          API_KEY="${GPR_PAT:-$GITHUB_TOKEN}"
          for nupkg in ./nupkg/*.${VER}.nupkg; do
            name="$(basename "$nupkg")"
            echo "→ Pushing $name to GPR..."
            set +e
            dotnet nuget push "$nupkg" \
              --source "https://nuget.pkg.github.com/$OWNER/index.json" \
              --api-key "$API_KEY" \
              --skip-duplicate
            rc=$?
            set -e
            if [ $rc -ne 0 ]; then
              # Tolleriamo il 403 solo per ProgesiCore (package già associato altrove)
              if [[ "$name" == ProgesiCore.* ]]; then
                echo "⚠️  GPR 403 su $name: probabilmente il package è associato ad un altro repo. Lo salto e continuo."
                continue
              fi
              exit $rc
            fi
          done
