name: release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # e.g. v1.0.40

permissions:
  contents: write
  packages: write

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # raccomandato per MinVer e changelog

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build -c Release --no-restore

      - name: Generate packlist (src only, skip Grasshopper)
        shell: bash
        run: |
          set -euo pipefail
          find ./src -name '*.csproj' \
            -not -path '*/ProgesiGrasshopperAssembly/*' \
            -print | sort > packlist.txt
          echo "Pack list:" && cat packlist.txt

      - name: Ensure per-project README placeholder (if missing)
        shell: bash
        run: |
          set -euo pipefail
          while IFS= read -r proj; do
            [[ -z "${proj:-}" ]] && continue
            dir="$(dirname "$proj")"
            if [[ ! -f "$dir/README.md" ]]; then
              name="$(basename "$dir")"
              printf '# %s\n\nCI placeholder README.\n' "$name" > "$dir/README.md"
              echo "Created placeholder $dir/README.md"
            fi
          done < packlist.txt

      - name: Pack (by packlist) via MinVer (versione dai tag)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ./nupkg
          while IFS= read -r proj; do
            [[ -z "${proj:-}" ]] && continue
            echo "Packing $proj"
            dotnet pack "$proj" -c Release --no-build -o ./nupkg
          done < packlist.txt
          echo "Produced packages:" && ls -l ./nupkg

      - name: Install dotnet-sourcelink (optional)
        shell: bash
        run: |
          set -euo pipefail
          dotnet tool update -g dotnet-sourcelink || true
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Verify packages (readme, snupkg, sourcelink)
        shell: pwsh
        run: pwsh -File ./tools/Verify-Packages.ps1 -NupkgDir ./nupkg

      - name: Build changelog (latest section)
        shell: pwsh
        run: pwsh -File ./tools/Build-Changelog.ps1

      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nupkg
          path: ./nupkg/*.nupkg

      - name: Upload latest changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: ./.changelog-LATEST.md

  release:
    needs: pack
    runs-on: ubuntu-latest
    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4
        with:
          name: nupkg
          path: ./nupkg

      - name: Download latest changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog
          path: .

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish to NuGet.org
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: bash
        run: |
          set -euo pipefail
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --api-key "$NUGET_API_KEY" \
            --skip-duplicate

      - name: Publish to GitHub Packages (GPR)
        if: startsWith(github.ref, 'refs/tags/')
        env:
          OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_PAT: ${{ secrets.GPR_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          TOKEN="${GPR_PAT:-}"
          if [[ -z "${TOKEN}" ]]; then
            TOKEN="${GITHUB_TOKEN}"
          fi
          for nupkg in ./nupkg/*.nupkg; do
            echo "-> Pushing $(basename "$nupkg") to GPR..."
            dotnet nuget push "$nupkg" \
              --source "https://nuget.pkg.github.com/$OWNER/index.json" \
              --api-key "$TOKEN" \
              --skip-duplicate
          done

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./nupkg/*.nupkg
          body_path: ./.changelog-LATEST.md
          generate_release_notes: true
