name: Release (tag)

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x
      - name: Determine package version from tag
        shell: pwsh
        run: |
          $tag='${{ github.ref_name }}'
          $ver=$tag.TrimStart('v','V')
          "PKG_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Version => $ver"
      - name: Restore
        run: dotnet restore Progesi.CI.slnf
      - name: Build
        run: dotnet build Progesi.CI.slnf -c Release --no-restore
      - name: Pack ProgesiCore
        run: dotnet pack src/ProgesiCore/ProgesiCore.csproj -c Release -o ./nuget /p:ContinuousIntegrationBuild=true /p:PackageVersion=${{ env.PKG_VERSION }}
      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/*.nupkg

  release:
    runs-on: ubuntu-latest
    needs: pack
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: nuget/*.nupkg
          generate_release_notes: true

      - name: Setup .NET (for push)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 1) Prova con GITHUB_TOKEN (best effort)
      - name: Publish to GitHub Packages using GITHUB_TOKEN (best-effort)
        continue-on-error: true
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name "github-token" \
            --username "${{ github.actor }}" \
            --password "${{ github.token }}" \
            --store-password-in-clear-text
          dotnet nuget push "./nuget/*.nupkg" --source "github-token" --skip-duplicate

      # 2) Fallback con PAT se disponibile
      - name: Publish to GitHub Packages using GPR_PAT (fallback)
        if: ${{ secrets.GPR_PAT != '' }}
        continue-on-error: true
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --name "github-pat" \
            --username "${{ github.repository_owner }}" \
            --password "${{ secrets.GPR_PAT }}" \
            --store-password-in-clear-text
          dotnet nuget push "./nuget/*.nupkg" --source "github-pat" --skip-duplicate

      # NuGet.org: non bloccare la release
      - name: Publish to NuGet.org (optional)
        if: ${{ secrets.NUGET_API_KEY != '' }}
        continue-on-error: true
        run: |
          dotnet nuget push "./nuget/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate \
            --api-key "${{ secrets.NUGET_API_KEY }}"
