name: Release (tag)

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            6.0.x
      - name: Determine package version from tag
        shell: pwsh
        run: |
          $tag='${{ github.ref_name }}'
          $ver=$tag.TrimStart('v','V')
          "PKG_VERSION=$ver" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8
          Write-Host "Version => $ver"
      - name: Restore
        run: dotnet restore Progesi.CI.slnf
      - name: Build
        run: dotnet build Progesi.CI.slnf -c Release --no-restore
      - name: Pack ProgesiCore
        run: dotnet pack src/ProgesiCore/ProgesiCore.csproj -c Release -o ./nuget /p:ContinuousIntegrationBuild=true /p:PackageVersion=${{ env.PKG_VERSION }}
      - name: Upload nupkg
        uses: actions/upload-artifact@v4
        with:
          name: nuget
          path: nuget/*.nupkg

  release:
    runs-on: ubuntu-latest
    needs: pack
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download nupkg
        uses: actions/download-artifact@v4
        with:
          name: nuget
          path: nuget

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: nuget/*.nupkg
          generate_release_notes: true

      - name: Setup .NET (push clients)
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # ✅ Forziamo l'autenticazione impostando NUGET_AUTH_TOKEN
      #    e usiamo direttamente l'URL .../index.json nello --source
      - name: Publish to GitHub Packages (try GITHUB_TOKEN)
        env:
          NUGET_AUTH_TOKEN: ${{ github.token }}
        continue-on-error: true
        run: |
          dotnet nuget push "nuget/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "x" \
            --skip-duplicate

      - name: Publish to GitHub Packages (fallback with PAT)
        if: ${{ secrets.GPR_PAT != '' }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GPR_PAT }}
        continue-on-error: true
        run: |
          dotnet nuget push "nuget/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "x" \
            --skip-duplicate

      - name: Publish to NuGet.org (optional)
        if: ${{ secrets.NUGET_API_KEY != '' }}
        continue-on-error: true
        run: |
          dotnet nuget push "nuget/*.nupkg" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate \
            --api-key "${{ secrets.NUGET_API_KEY }}"
