name: Semantic PR

on:
  pull_request_target:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read

jobs:
  lint:
    # Evita rossi sulle PR di Dependabot (titoli non in formato Conventional Commits)
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Tipi consentiti (Conventional Commits)
          types: |
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            test
          # Imposta a true se vuoi obbligare anche lo "scope"
          requireScope: false
          # Facoltativo: aggiungi questa label alla PR per saltare il controllo
          ignoreLabels: |
            skip-semantic-pr
