name: Semantic PR

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review, labeled]

permissions:
  pull-requests: read

concurrency:
  group: semanticpr-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    if: github.actor != 'dependabot[bot]' # bypass per Dependabot
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: false
          subjectPattern: ".+"
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            build
            ci
