name: Semantic PR

on:
  pull_request_target:

permissions:
  pull-requests: read

jobs:
  lint:
    # non controllare i PR aperti da dependabot
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            chore,ci,docs,feat,fix,perf,refactor,test
